name: Publish Updates
on:
  push:
    branches: 
      - 'main'
    paths:
      - 'dependency.lic'
      - 'noop.lic'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3']
    name: Publish Updates
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '20'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Release updates to Tillmen's Lich repository
        env:
          AUTHOR: ${{ secrets.repo_author }}
          PASSWORD: ${{ secrets.repo_password }}
          TRAVIS_COMMIT: ${{ github.sha }}
          TRAVIS_COMMIT_RANGE: ${{ github.event.before }}..${{ github.sha }}
        run: bin/repo
