name: Valid Ruby syntax
on: [push, pull_request]

jobs:
  check_syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
    name: Run tests on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.lic
            *.rb

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Run Ruby syntax check on changed scripts
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ruby -c ${file}
          done
